import {
  Database,
  HardDrive,
  Code,
  Server,
  Boxes,
  Cloud,
  Activity,
  Layout,
  Shield,
  Brain,
  Cpu,
  GitBranch,
  Terminal,
  BookOpen,
  Calculator,
  Sigma,
  Star,
  Briefcase,
  Layers,
} from "lucide-react";

export const categories = [
  {
    id: "data-engineering",
    name: "Data Engineering",
    icon: Database,
    color: "blue",
    technologies: [
      {
        id: "kafka",
        name: "Apache Kafka",
        hasVisualizer: true,
        hasDoc: true,
        docComponent: "KafkaDocs",
        badge: "Streaming",
      },
      {
        id: "spark",
        name: "Apache Spark",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "SparkDocs",
        badge: "Processing",
      },
      {
        id: "airflow",
        name: "Apache Airflow",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "AirflowDocs",
        badge: "Orchestration",
      },
      {
        id: "flink",
        name: "Apache Flink",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "FlinkDocs",
        badge: "Stream Processing",
      },
      // {
      //   id: "dbt",
      //   name: "dbt",
      //   hasVisualizer: false,
      //   hasDoc: true,
      //   docComponent: "DbtDocs",
      //   badge: "Transformation",
      // },
      // {
      //   id: "databricks",
      //   name: "Databricks",
      //   hasVisualizer: false,
      //   hasDoc: false,
      //   badge: "Unified Analytics",
      //   comingSoon: true,
      // },
      // {
      //   id: "deltalake",
      //   name: "Delta Lake",
      //   hasVisualizer: false,
      //   hasDoc: false,
      //   badge: "Storage Layer",
      //   comingSoon: true,
      // },
      // {
      //   id: "presto",
      //   name: "Presto / Trino",
      //   hasVisualizer: false,
      //   hasDoc: false,
      //   badge: "Distributed SQL",
      //   comingSoon: true,
      // },
      // {
      //   id: "beam",
      //   name: "Apache Beam",
      //   hasVisualizer: false,
      //   hasDoc: false,
      //   badge: "Unified Model",
      //   comingSoon: true,
      // },
      // {
      //   id: "s3",
      //   name: "Amazon S3",
      //   hasVisualizer: false,
      //   hasDoc: false,
      //   badge: "Object Storage",
      //   comingSoon: true,
      // },
      {
        id: "parquet",
        name: "Apache Parquet",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "ParquetDocs",
        badge: "Columnar Format",
      },
      {
        id: "avro",
        name: "Apache Avro",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "AvroDocs",
        badge: "Serialization",
      },
      {
        id: "protobuf",
        name: "Protocol Buffers",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "ProtobufDocs",
        badge: "RPC Serialization",
      },
      {
        id: "iceberg",
        name: "Apache Iceberg",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "IcebergDocs",
        badge: "Table Format",
      },
      {
        id: "snowflake",
        name: "Snowflake",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "SnowflakeDocs",
        badge: "Data Warehouse",
      },
    ],
  },
  {
    id: "databases",
    name: "Databases",
    icon: HardDrive,
    color: "purple",
    technologies: [
      {
        id: "sql",
        name: "PostgreSQL / SQL",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "SQLDocs",
        badge: "Relational",
      },
      {
        id: "redis",
        name: "Redis",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "RedisDocs",
        badge: "In-Memory",
      },
      {
        id: "mongodb",
        name: "MongoDB",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "MongoDBDocs",
        badge: "Document",
      },
      {
        id: "cassandra",
        name: "Apache Cassandra",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CassandraDocs",
        badge: "Wide-Column",
      },
      // {
      //   id: "clickhouse",
      //   name: "ClickHouse",
      //   hasVisualizer: false,
      //   hasDoc: false,
      //   badge: "OLAP",
      //   comingSoon: true,
      // },
      {
        id: "dynamodb",
        name: "DynamoDB",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "DynamoDBDocs",
        badge: "Key-Value",
      },
      {
        id: "elasticsearch",
        name: "Elasticsearch",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "ElasticsearchDocs",
        badge: "Search",
      },
      {
        id: "neo4j",
        name: "Neo4j",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "Neo4jDocs",
        badge: "Graph",
      },
    ],
  },
  {
    id: "backend-engineering",
    name: "Backend Engineering",
    icon: Code,
    color: "green",
    technologies: [
      {
        id: "nodejs",
        name: "Node.js",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "NodeJSDocs",
        badge: "Runtime",
      },
      {
        id: "python",
        name: "Python FastAPI",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "FastAPIDocs",
        badge: "Framework",
      },
      {
        id: "java",
        name: "Java Spring Boot",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "SpringBootDocs",
        badge: "Framework",
      },
      {
        id: "graphql",
        name: "GraphQL",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "GraphQLDocs",
        badge: "Query Language",
      },
      {
        id: "grpc",
        name: "gRPC",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "GrpcDocs",
        badge: "RPC Framework",
      },
      {
        id: "rabbitmq",
        name: "RabbitMQ",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "RabbitMQDocs",
        badge: "Message Broker",
      },
      {
        id: "websockets",
        name: "WebSockets",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "WebSocketsDocs",
        badge: "Real-time",
      },
    ],
  },
  {
    id: "devops-engineering",
    name: "DevOps Engineering",
    icon: Server,
    color: "red",
    technologies: [
      {
        id: "kubernetes",
        name: "Kubernetes",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "KubernetesDocs",
        badge: "Orchestration",
      },
      {
        id: "docker",
        name: "Docker",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "DockerDocs",
        badge: "Containerization",
      },
      {
        id: "helm",
        name: "Helm",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HelmDocs",
        badge: "Package Manager",
      },
      {
        id: "terraform",
        name: "Terraform",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "TerraformDocs",
        badge: "IaC",
      },
    ],
  },
  {
    id: "frontend-engineering",
    name: "Frontend Engineering",
    icon: Layout,
    color: "pink",
    technologies: [
      {
        id: "react",
        name: "React",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "ReactDocs",
        badge: "Library",
      },
      {
        id: "nextjs",
        name: "Next.js",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "NextJSDocs",
        badge: "Framework",
      },
      {
        id: "tailwind",
        name: "Tailwind CSS",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "TailwindDocs",
        badge: "Styling",
      },
      {
        id: "state-mgmt",
        name: "Redux",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "ReduxDocs",
        badge: "State Mgmt",
      },
    ],
  },
  {
    id: "programming-languages",
    name: "Programming Languages",
    icon: Terminal,
    color: "cyan",
    technologies: [
      {
        id: "cpp-lang",
        name: "C++",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "programming-languages",
        badge: "Systems",
        comingSoon: false,
      },
      {
        id: "java-lang",
        name: "Java",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "java",
        badge: "OOP & JVM",
        comingSoon: false,
      },
      {
        id: "python-lang",
        name: "Python",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "python",
        badge: "Dynamic",
        comingSoon: false,
      },
      {
        id: "javascript-lang",
        name: "JavaScript",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "javascript",
        badge: "Event Loop",
        comingSoon: false,
      },
      {
        id: "go-lang",
        name: "Go",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "go",
        badge: "Concurrency",
        comingSoon: false,
      },
    ],
  },
  {
    id: "system-design",
    name: "High Level Design",
    icon: Activity,
    color: "indigo",
    technologies: [
      {
        id: "scalability",
        name: "Scalability & Availability",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HLDDocs",
        badge: "Concepts",
      },
      {
        id: "load-balancing",
        name: "Load Balancing",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HLDDocs",
        badge: "Distribution",
      },
      {
        id: "caching-patterns",
        name: "Caching Patterns",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HLDDocs",
        badge: "Performance",
      },
      {
        id: "sharding",
        name: "Database Sharding",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HLDDocs",
        badge: "Data Scale",
      },
      {
        id: "cap-theorem",
        name: "CAP Theorem",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HLDDocs",
        badge: "Theory",
      },
      {
        id: "distributed-consensus",
        name: "Distributed Consensus",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HLDDocs",
        badge: "Paxos/Raft",
      },
      {
        id: "system-design-resources",
        name: "System Design Resources",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "SystemDesignResources",
        badge: "Resources",
      },
    ],
  },
  {
    id: "low-level-design",
    name: "Low Level Design",
    icon: Layout,
    color: "orange",
    technologies: [
      {
        id: "design-patterns",
        name: "Design Patterns",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "DesignPatterns",
        badge: "Gang of Four",
      },
      {
        id: "lld-examples",
        name: "LLD Examples",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "LLDExamples",
        badge: "Object Oriented",
      },
    ],
  },
  {
    id: "dsa",
    name: "Data Structures & Algo",
    icon: GitBranch,
    color: "teal",
    technologies: [
      {
        id: "standard-patterns",
        name: "14 Standard Patterns",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "StandardPatternsDocs",
        badge: "Must Know",
      },
      {
        id: "leetcode-problems",
        name: "LeetCode Problem List",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "LeetCodeDocs",
        badge: "100+ Problems",
      },
      {
        id: "arrays",
        name: "Arrays & Bit Manipulation",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "ArraysDocs",
        badge: "Fundamental",
      },
      {
        id: "stack",
        name: "Stack",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "StackDocs",
        badge: "LIFO",
      },
      {
        id: "heap",
        name: "Heap & Priority Queue",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HeapDocs",
        badge: "Top K",
      },
      {
        id: "queue",
        name: "Queue",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "QueueDocs",
        badge: "FIFO",
      },
      {
        id: "backtracking",
        name: "Backtracking",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "BacktrackingDocs",
        badge: "Recursion",
      },
      {
        id: "binary-search",
        name: "Binary Search",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "BinarySearchDocs",
        badge: "Divide",
      },
      {
        id: "strings",
        name: "Strings",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "StringDocs",
        badge: "Patterns",
      },
      {
        id: "trees",
        name: "Trees",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "TreeDocs",
        badge: "Hierarchical",
      },
      {
        id: "graphs",
        name: "Graphs",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "GraphDocs",
        badge: "Networks",
      },
      {
        id: "dp",
        name: "Dynamic Programming",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "DynamicProgramming",
        badge: "Optimization",
      },
    ],
  },
  {
    id: "hld-books",
    name: "HLD Books",
    icon: Layout,
    color: "amber",
    technologies: [
      {
        id: "ddia",
        name: "Designing Data-Intensive Applications",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "DDIABook",
        badge: "Martin Kleppmann",
      },
      {
        id: "database-internals",
        name: "Database Internals",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "DatabaseInternalsBook",
        badge: "Alex Petrov",
      },
    ],
  },
  {
    id: "math-books",
    name: "Mathematics Books",
    icon: Sigma,
    color: "indigo",
    technologies: [
      {
        id: "complex-analysis-spiegel",
        name: "Complex Analysis",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "ComplexAnalysisBook",
        badge: "Schaum's",
      },
      {
        id: "linear-algebra-lipschutz",
        name: "Linear Algebra",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "LinearAlgebraBook",
        badge: "Schaum's",
      },
    ],
  },
  {
    id: "ai-books",
    name: "AI Books",
    icon: Brain,
    color: "fuchsia",
    technologies: [
      {
        id: "deep-learning-goodfellow",
        name: "Deep Learning",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "DeepLearningBook",
        badge: "Ian Goodfellow",
      },
      {
        id: "pattern-recognition-bishop",
        name: "Pattern Recognition",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "PatternRecognitionBook",
        badge: "C. Bishop",
      },
    ],
  },
  {
    id: "finance-books",
    name: "Finance Books",
    icon: Calculator,
    color: "green",
    technologies: [
      {
        id: "hull-options",
        name: "Options, Futures & Derivatives",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HullBook",
        badge: "John Hull",
      },
      {
        id: "security-analysis",
        name: "Security Analysis",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "SecurityAnalysisBook",
        badge: "Graham & Dodd",
      },
      
    ],
  },
  // {
  //   id: "physics-books",
  //   name: "Physics Books",
  //   icon: Activity,
  //   color: "sky",
  //   technologies: [
  //     {
  //       id: "feynman-lectures",
  //       name: "Feynman Lectures",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "Richard Feynman",
  //       comingSoon: true,
  //     },
  //     {
  //       id: "griffiths-quantum",
  //       name: "Intro to Quantum Mechanics",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "Griffiths",
  //       comingSoon: true,
  //     },
  //     {
  //       id: "spacetime-physics",
  //       name: "Spacetime Physics",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "Taylor & Wheeler",
  //       comingSoon: true,
  //     },
  //     {
  //       id: "goldstein-mechanics",
  //       name: "Classical Mechanics",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "Goldstein",
  //       comingSoon: true,
  //     },
  //   ],
  // },
  // {
  //   id: "philosophy-books",
  //   name: "Philosophy Books",
  //   icon: BookOpen,
  //   color: "purple",
  //   technologies: [
  //     {
  //       id: "meditations-aurelius",
  //       name: "Meditations",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "Marcus Aurelius",
  //       comingSoon: true,
  //     },
  //     {
  //       id: "republic-plato",
  //       name: "The Republic",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "Plato",
  //       comingSoon: true,
  //     },
  //     {
  //       id: "critique-pure-reason",
  //       name: "Critique of Pure Reason",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "Kant",
  //       comingSoon: true,
  //     },
  //     {
  //       id: "being-and-time",
  //       name: "Being and Time",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "Heidegger",
  //       comingSoon: true,
  //     },
  //   ],
  // },
  // {
  //   id: "psychology-books",
  //   name: "Psychology Books",
  //   icon: Brain,
  //   color: "amber",
  //   technologies: [
  //     {
  //       id: "thinking-fast-slow",
  //       name: "Thinking, Fast and Slow",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "Kahneman",
  //       comingSoon: true,
  //     },
  //     {
  //       id: "influence-cialdini",
  //       name: "Influence",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "Cialdini",
  //       comingSoon: true,
  //     },
  //     {
  //       id: "mans-search-meaning",
  //       name: "Man's Search for Meaning",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "Frankl",
  //       comingSoon: true,
  //     },
  //   ],
  // },
  // {
  //   id: "poetry-books",
  //   name: "Poetry Books",
  //   icon: Star,
  //   color: "red",
  //   technologies: [
  //     {
  //       id: "odyssey-homer",
  //       name: "The Odyssey",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "Homer",
  //       comingSoon: true,
  //     },
  //     {
  //       id: "paradise-lost",
  //       name: "Paradise Lost",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "Milton",
  //       comingSoon: true,
  //     },
  //     {
  //       id: "leaves-of-grass",
  //       name: "Leaves of Grass",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "Whitman",
  //       comingSoon: true,
  //     },
  //     {
  //       id: "waste-land",
  //       name: "The Waste Land",
  //       hasVisualizer: false,
  //       hasDoc: false,
  //       badge: "T.S. Eliot",
  //       comingSoon: true,
  //     },
  //   ],
  // },
  {
    id: "finance",
    name: "Finance",
    icon: Calculator,
    color: "green",
    technologies: [
      {
        id: "finance-overview",
        name: "Finance",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "finance",
        badge: "Quant",
      },
    ],
  },
  {
    id: "mathematics",
    name: "Mathematics",
    icon: Sigma,
    color: "indigo",
    technologies: [
      {
        id: "mathematics-overview",
        name: "Mathematics",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "mathematics",
        badge: "Theory",
      },
    ],
  },
  {
    id: "ai-engineering",
    name: "AI & ML Engineering",
    icon: Brain,
    color: "fuchsia",
    technologies: [
      {
        id: "ml-overview",
        name: "Machine Learning",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "machine-learning",
        badge: "AI/ML",
      },
    ],
  },
  // {
  //   id: "philosophy",
  //   name: "Philosophy",
  //   icon: BookOpen,
  //   color: "purple",
  //   technologies: [
  //     {
  //       id: "philosophy-overview",
  //       name: "Philosophy",
  //       hasVisualizer: false,
  //       hasDoc: true,
  //       docComponent: "CategoryPage",
  //       categoryData: "philosophy",
  //       badge: "Wisdom",
  //     },
  //   ],
  // },
  // {
  //   id: "psychology",
  //   name: "Psychology",
  //   icon: Brain,
  //   color: "amber",
  //   technologies: [
  //     {
  //       id: "psychology-overview",
  //       name: "Psychology",
  //       hasVisualizer: false,
  //       hasDoc: true,
  //       docComponent: "CategoryPage",
  //       categoryData: "psychology",
  //       badge: "Mind",
  //     },
  //   ],
  // },
  // {
  //   id: "poetry",
  //   name: "Poetry",
  //   icon: Star,
  //   color: "red",
  //   technologies: [
  //     {
  //       id: "poetry-overview",
  //       name: "Poetry",
  //       hasVisualizer: false,
  //       hasDoc: true,
  //       docComponent: "CategoryPage",
  //       categoryData: "poetry",
  //       badge: "Arts",
  //     },
  //   ],
  // },
  // {
  //   id: "physics",
  //   name: "Physics",
  //   icon: Activity,
  //   color: "sky",
  //   technologies: [
  //     {
  //       id: "physics-overview",
  //       name: "Physics",
  //       hasVisualizer: false,
  //       hasDoc: true,
  //       docComponent: "CategoryPage",
  //       categoryData: "physics",
  //       badge: "Science",
  //     },
  //   ],
  // },
];

export const superCategories = [
  {
    id: "software-engineering",
    name: "Software Engineering",
    icon: Layers,
    color: "blue",
    categoryIds: [
      "data-engineering",
      "databases",
      "backend-engineering",
      "devops-engineering",
      "frontend-engineering",
      "programming-languages",
    ],
  },
  {
    id: "interviews",
    name: "Interviews",
    icon: Briefcase,
    color: "orange",
    categoryIds: ["dsa", "system-design", "low-level-design"],
  },
  {
    id: "books-gallery",
    name: "Books",
    icon: BookOpen,
    color: "teal",
    categoryIds: ["hld-books", "math-books", "ai-books", "finance-books"],
    //  "physics-books",
    //  "philosophy-books",
    //  "psychology-books",
    //  "poetry-books",
    //],
  },
  {
    id: "interests",
    name: "Interests",
    icon: Star,
    color: "green",
    layout: "direct",
    categoryIds: [
      "finance",
      "mathematics",
      "ai-engineering",
      // "philosophy",
      // "psychology",
      // "poetry",
      // "physics",
    ],
  },
];

// Helper to get technology by ID across all categories
export const getTechnologyById = (techId) => {
  for (const category of categories) {
    const tech = category.technologies.find((t) => t.id === techId);
    if (tech) {
      return { ...tech, category };
    }
  }
  return null;
};

// Helper to get category by ID
export const getCategoryById = (categoryId) => {
  return categories.find((c) => c.id === categoryId);
};
