import {
  Activity,
  BookOpen,
  Brain,
  Briefcase,
  Calculator,
  Code,
  Database,
  GitBranch,
  HardDrive,
  Layers,
  Layout,
  Server,
  Sigma,
  Star,
  Terminal,
} from "lucide-react";

export const categories = [
  {
    id: "data-engineering",
    name: "Data Engineering",
    icon: Database,
    color: "blue",
    technologies: [
      {
        id: "kafka",
        name: "Apache Kafka",
        hasVisualizer: true,
        hasDoc: true,
        docComponent: "KafkaDocs",
        badge: "Streaming",
      },
      {
        id: "spark",
        name: "Apache Spark",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "SparkDocs",
        badge: "Processing",
      },
      {
        id: "airflow",
        name: "Apache Airflow",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "AirflowDocs",
        badge: "Orchestration",
      },
      {
        id: "flink",
        name: "Apache Flink",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "FlinkDocs",
        badge: "Stream Processing",
      },
      {
        id: "parquet",
        name: "Apache Parquet",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "ParquetDocs",
        badge: "Columnar Format",
      },
      {
        id: "avro",
        name: "Apache Avro",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "AvroDocs",
        badge: "Serialization",
      },
      {
        id: "protobuf",
        name: "Protocol Buffers",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "ProtobufDocs",
        badge: "RPC Serialization",
      },
      {
        id: "iceberg",
        name: "Apache Iceberg",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "IcebergDocs",
        badge: "Table Format",
      },
      {
        id: "snowflake",
        name: "Snowflake",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "SnowflakeDocs",
        badge: "Data Warehouse",
      },
    ],
  },
  {
    id: "databases",
    name: "Databases",
    icon: HardDrive,
    color: "purple",
    technologies: [
      {
        id: "sql",
        name: "PostgreSQL / SQL",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "SQLDocs",
        badge: "Relational",
      },
      {
        id: "redis",
        name: "Redis",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "RedisDocs",
        badge: "In-Memory",
      },
      {
        id: "mongodb",
        name: "MongoDB",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "MongoDBDocs",
        badge: "Document",
      },
      {
        id: "cassandra",
        name: "Apache Cassandra",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CassandraDocs",
        badge: "Wide-Column",
      },
      {
        id: "dynamodb",
        name: "DynamoDB",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "DynamoDBDocs",
        badge: "Key-Value",
      },
      {
        id: "elasticsearch",
        name: "Elasticsearch",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "ElasticsearchDocs",
        badge: "Search",
      },
      {
        id: "neo4j",
        name: "Neo4j",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "Neo4jDocs",
        badge: "Graph",
      },
    ],
  },
  {
    id: "backend-engineering",
    name: "Backend Engineering",
    icon: Code,
    color: "green",
    technologies: [
      {
        id: "nodejs",
        name: "Node.js",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "NodeJSDocs",
        badge: "Runtime",
      },
      {
        id: "python",
        name: "Python FastAPI",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "FastAPIDocs",
        badge: "Framework",
      },
      {
        id: "java",
        name: "Java Spring Boot",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "SpringBootDocs",
        badge: "Framework",
      },
      {
        id: "graphql",
        name: "GraphQL",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "GraphQLDocs",
        badge: "Query Language",
      },
      {
        id: "grpc",
        name: "gRPC",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "GrpcDocs",
        badge: "RPC Framework",
      },
      {
        id: "rabbitmq",
        name: "RabbitMQ",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "RabbitMQDocs",
        badge: "Message Broker",
      },
      {
        id: "websockets",
        name: "WebSockets",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "WebSocketsDocs",
        badge: "Real-time",
      },
    ],
  },
  {
    id: "devops-engineering",
    name: "DevOps Engineering",
    icon: Server,
    color: "red",
    technologies: [
      {
        id: "kubernetes",
        name: "Kubernetes",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "KubernetesDocs",
        badge: "Orchestration",
      },
      {
        id: "docker",
        name: "Docker",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "DockerDocs",
        badge: "Containerization",
      },
      {
        id: "helm",
        name: "Helm",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HelmDocs",
        badge: "Package Manager",
      },
      {
        id: "terraform",
        name: "Terraform",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "TerraformDocs",
        badge: "IaC",
      },
    ],
  },
  {
    id: "frontend-engineering",
    name: "Frontend Engineering",
    icon: Layout,
    color: "pink",
    technologies: [
      {
        id: "react",
        name: "React",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "ReactDocs",
        badge: "Library",
      },
      {
        id: "nextjs",
        name: "Next.js",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "NextJSDocs",
        badge: "Framework",
      },
      {
        id: "tailwind",
        name: "Tailwind CSS",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "TailwindDocs",
        badge: "Styling",
      },
      {
        id: "state-mgmt",
        name: "Redux",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "ReduxDocs",
        badge: "State Mgmt",
      },
    ],
  },
  {
    id: "programming-languages",
    name: "Programming Languages",
    icon: Terminal,
    color: "cyan",
    technologies: [
      {
        id: "cpp-lang",
        name: "C++",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "programming-languages",
        badge: "Systems",
        comingSoon: false,
      },
      {
        id: "java-lang",
        name: "Java",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "java",
        badge: "OOP & JVM",
        comingSoon: false,
      },
      {
        id: "python-lang",
        name: "Python",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "python",
        badge: "Dynamic",
        comingSoon: false,
      },
      {
        id: "javascript-lang",
        name: "JavaScript",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "javascript",
        badge: "Event Loop",
        comingSoon: false,
      },
      {
        id: "go-lang",
        name: "Go",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "go",
        badge: "Concurrency",
        comingSoon: false,
      },
    ],
  },
  {
    id: "system-design",
    name: "High Level Design",
    icon: Activity,
    color: "indigo",
    technologies: [
      {
        id: "scalability",
        name: "Scalability & Availability",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HLDDocs",
        badge: "Concepts",
      },
      {
        id: "load-balancing",
        name: "Load Balancing",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HLDDocs",
        badge: "Distribution",
      },
      {
        id: "caching-patterns",
        name: "Caching Patterns",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HLDDocs",
        badge: "Performance",
      },
      {
        id: "sharding",
        name: "Database Sharding",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HLDDocs",
        badge: "Data Scale",
      },
      {
        id: "cap-theorem",
        name: "CAP Theorem",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HLDDocs",
        badge: "Theory",
      },
      {
        id: "distributed-consensus",
        name: "Distributed Consensus",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HLDDocs",
        badge: "Paxos/Raft",
      },
      {
        id: "system-design-resources",
        name: "System Design Resources",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "SystemDesignResources",
        badge: "Resources",
      },
    ],
  },
  {
    id: "low-level-design",
    name: "Low Level Design",
    icon: Layout,
    color: "orange",
    technologies: [
      {
        id: "design-patterns",
        name: "Design Patterns",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "DesignPatterns",
        badge: "Gang of Four",
      },
      {
        id: "lld-examples",
        name: "LLD Examples",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "LLDExamples",
        badge: "Object Oriented",
      },
    ],
  },
  {
    id: "dsa",
    name: "DSA",
    icon: GitBranch,
    color: "teal",
    technologies: [
      {
        id: "standard-patterns",
        name: "14 Standard Patterns",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "StandardPatternsDocs",
        badge: "Must Know",
      },
      {
        id: "leetcode-problems",
        name: "LeetCode Problem List",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "LeetCodeDocs",
        badge: "100+ Problems",
      },
      {
        id: "arrays",
        name: "Arrays & Bit Manipulation",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "ArraysDocs",
        badge: "Fundamental",
      },
      {
        id: "stack",
        name: "Stack",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "StackDocs",
        badge: "LIFO",
      },
      {
        id: "heap",
        name: "Heap & Priority Queue",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HeapDocs",
        badge: "Top K",
      },
      {
        id: "queue",
        name: "Queue",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "QueueDocs",
        badge: "FIFO",
      },
      {
        id: "backtracking",
        name: "Backtracking",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "BacktrackingDocs",
        badge: "Recursion",
      },
      {
        id: "binary-search",
        name: "Binary Search",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "BinarySearchDocs",
        badge: "Divide",
      },
      {
        id: "strings",
        name: "Strings",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "StringDocs",
        badge: "Patterns",
      },
      {
        id: "trees",
        name: "Trees",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "TreeDocs",
        badge: "Hierarchical",
      },
      {
        id: "graphs",
        name: "Graphs",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "GraphDocs",
        badge: "Networks",
      },
      {
        id: "dp",
        name: "Dynamic Programming",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "DynamicProgramming",
        badge: "Optimization",
      },
    ],
  },
  {
    id: "sde-books",
    name: "SDE Books",
    icon: Layout,
    color: "amber",
    technologies: [
      {
        id: "ddia",
        name: "Designing Data-Intensive Applications",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "DDIABook",
        badge: "Martin Kleppmann",
      },
      {
        id: "database-internals",
        name: "Database Internals",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "DatabaseInternalsBook",
        badge: "Alex Petrov",
      },
    ],
  },
  {
    id: "math-books",
    name: "Mathematics Books",
    icon: Sigma,
    color: "indigo",
    technologies: [
      {
        id: "complex-analysis-spiegel",
        name: "Complex Analysis",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "ComplexAnalysisBook",
        badge: "Schaum's",
      },
      {
        id: "linear-algebra-lipschutz",
        name: "Linear Algebra",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "LinearAlgebraBook",
        badge: "Schaum's",
      },
    ],
  },
  {
    id: "ai-books",
    name: "AI Books",
    icon: Brain,
    color: "fuchsia",
    technologies: [
      {
        id: "deep-learning-goodfellow",
        name: "Deep Learning",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "DeepLearningBook",
        badge: "Ian Goodfellow",
      },
      {
        id: "pattern-recognition-bishop",
        name: "Pattern Recognition",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "PatternRecognitionBook",
        badge: "C. Bishop",
      },
    ],
  },
  {
    id: "finance-books",
    name: "Finance Books",
    icon: Calculator,
    color: "green",
    technologies: [
      {
        id: "hull-options",
        name: "Options, Futures & Derivatives",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "HullBook",
        badge: "John Hull",
      },
      {
        id: "security-analysis",
        name: "Security Analysis",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "SecurityAnalysisBook",
        badge: "Graham & Dodd",
      },
    ],
  },
  {
    id: "finance",
    name: "Finance",
    icon: Calculator,
    color: "green",
    technologies: [
      {
        id: "finance-overview",
        name: "Finance",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "finance",
        badge: "Quant",
      },
    ],
  },
  {
    id: "mathematics",
    name: "Mathematics",
    icon: Sigma,
    color: "indigo",
    technologies: [
      {
        id: "mathematics-overview",
        name: "Mathematics",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "mathematics",
        badge: "Theory",
      },
    ],
  },
  {
    id: "ai-engineering",
    name: "AI & ML Engineering",
    icon: Brain,
    color: "fuchsia",
    technologies: [
      {
        id: "ml-overview",
        name: "Machine Learning",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "machine-learning",
        badge: "AI/ML",
      },
    ],
  },
  {
    id: "prompt-engineering",
    name: "Prompt Engineering",
    icon: Terminal,
    color: "purple",
    technologies: [
      {
        id: "prompt-engineering-overview",
        name: "Prompt Engineering",
        hasVisualizer: false,
        hasDoc: true,
        docComponent: "CategoryPage",
        categoryData: "prompt-engineering",
        badge: "AI",
      },
    ],
  },
];

export const superCategories = [
  {
    id: "software-engineering",
    name: "SDE",
    icon: Layers,
    color: "blue",
    categoryIds: [
      "sde-books",
      "data-engineering",
      "databases",
      "backend-engineering",
      "devops-engineering",
      "frontend-engineering",
      "programming-languages",
    ],
  },
  {
    id: "interviews",
    name: "Interviews",
    icon: Briefcase,
    color: "orange",
    categoryIds: ["dsa", "system-design", "low-level-design"],
  },
  {
    id: "finance",
    name: "Finance",
    icon: Calculator,
    color: "green",
    categoryIds: ["finance-books", "finance"],
  },
  {
    id: "mathematics",
    name: "Mathematics",
    icon: Sigma,
    color: "indigo",
    categoryIds: ["math-books", "mathematics"],
  },
  {
    id: "ai-technologies",
    name: "AI & ML",
    icon: Brain,
    color: "fuchsia",
    categoryIds: ["ai-books", "ai-engineering", "ml-overview", "prompt-engineering"],
  }
];

// Helper to get technology by ID across all categories
export const getTechnologyById = (techId) => {
  for (const category of categories) {
    const tech = category.technologies.find((t) => t.id === techId);
    if (tech) {
      return { ...tech, category };
    }
  }
  return null;
};

// Helper to get category by ID
export const getCategoryById = (categoryId) => {
  return categories.find((c) => c.id === categoryId);
};
