import { Database, HardDrive, Code, Server, Boxes, Cloud, Activity, Layout, Shield, Brain, Cpu, GitBranch, Terminal } from 'lucide-react';

export const categories = [
  {
    id: 'data-engineering',
    name: 'Data Engineering',
    icon: Database,
    color: 'blue',
    technologies: [
      {
        id: 'kafka',
        name: 'Apache Kafka',
        hasVisualizer: true,
        hasDoc: true,
        docComponent: 'KafkaDocs',
        badge: 'Streaming',
      },
      {
        id: 'spark',
        name: 'Apache Spark',
        hasVisualizer: false,
        hasDoc: true,
        docComponent: 'SparkDocs',
        badge: 'Processing',
      },
      {
        id: 'airflow',
        name: 'Apache Airflow',
        hasVisualizer: false,
        hasDoc: true,
        docComponent: 'AirflowDocs',
        badge: 'Orchestration',
      },
      {
        id: 'flink',
        name: 'Apache Flink',
        hasVisualizer: false,
        hasDoc: true,
        docComponent: 'FlinkDocs',
        badge: 'Stream Processing',
      },
      {
        id: 'dbt',
        name: 'dbt',
        hasVisualizer: false,
        hasDoc: true,
        docComponent: 'DbtDocs',
        badge: 'Transformation',
      },
      {
        id: 'databricks',
        name: 'Databricks',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Unified Analytics',
        comingSoon: true,
      },
      {
        id: 'snowflake',
        name: 'Snowflake',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Data Warehouse',
        comingSoon: true,
      },
      {
        id: 'deltalake',
        name: 'Delta Lake',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Storage Layer',
        comingSoon: true,
      },
      {
        id: 'presto',
        name: 'Presto / Trino',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Distributed SQL',
        comingSoon: true,
      },
      {
        id: 'beam',
        name: 'Apache Beam',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Unified Model',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'databases',
    name: 'Databases',
    icon: HardDrive,
    color: 'purple',
    technologies: [
      {
        id: 'sql',
        name: 'PostgreSQL / SQL',
        hasVisualizer: false,
        hasDoc: true,
        docComponent: 'SQLDocs',
        badge: 'Relational',
      },
      {
        id: 'redis',
        name: 'Redis',
        hasVisualizer: false,
        hasDoc: true,
        docComponent: 'RedisDocs',
        badge: 'In-Memory',
      },
      {
        id: 'mongodb',
        name: 'MongoDB',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Document',
        comingSoon: true,
      },
      {
        id: 'cassandra',
        name: 'Cassandra',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Wide Column',
        comingSoon: true,
      },
      {
        id: 'clickhouse',
        name: 'ClickHouse',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'OLAP',
        comingSoon: true,
      },
      {
        id: 'dynamodb',
        name: 'DynamoDB',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Key-Value',
        comingSoon: true,
      },
      {
        id: 'elasticsearch',
        name: 'Elasticsearch',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Search Engine',
        comingSoon: true,
      },
      {
        id: 'neo4j',
        name: 'Neo4j',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Graph',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'backend-engineering',
    name: 'Backend Engineering',
    icon: Code,
    color: 'green',
    technologies: [
      {
        id: 'nodejs',
        name: 'Node.js',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Runtime',
        comingSoon: true,
      },
      {
        id: 'python',
        name: 'Python (FastAPI)',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Framework',
        comingSoon: true,
      },
      {
        id: 'go',
        name: 'Go',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Language',
        comingSoon: true,
      },
      {
        id: 'java',
        name: 'Java Spring Boot',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Framework',
        comingSoon: true,
      },
      {
        id: 'graphql',
        name: 'GraphQL',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Query Language',
        comingSoon: true,
      },
      {
        id: 'grpc',
        name: 'gRPC',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'RPC Framework',
        comingSoon: true,
      },
      {
        id: 'rabbitmq',
        name: 'RabbitMQ',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Message Broker',
        comingSoon: true,
      },
      {
        id: 'websockets',
        name: 'WebSockets',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Real-time',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'data-storage',
    name: 'Data Storage & Formats',
    icon: Boxes,
    color: 'orange',
    technologies: [
      {
        id: 's3',
        name: 'Amazon S3',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Object Storage',
        comingSoon: true,
      },
      {
        id: 'parquet',
        name: 'Apache Parquet',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Columnar Format',
        comingSoon: true,
      },
      {
        id: 'avro',
        name: 'Apache Avro',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Serialization',
        comingSoon: true,
      },
      {
        id: 'iceberg',
        name: 'Apache Iceberg',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Table Format',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'devops-engineering',
    name: 'DevOps Engineering',
    icon: Server,
    color: 'red',
    technologies: [
      {
        id: 'kubernetes',
        name: 'Kubernetes',
        hasVisualizer: false,
        hasDoc: true,
        docComponent: 'KubernetesDocs',
        badge: 'Orchestration',
      },
      {
        id: 'docker',
        name: 'Docker',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Containerization',
        comingSoon: true,
      },
      {
        id: 'helm',
        name: 'Helm',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Package Manager',
        comingSoon: true,
      },
      {
        id: 'terraform',
        name: 'Terraform',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'IaC',
        comingSoon: true,
      },
      {
        id: 'ansible',
        name: 'Ansible',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Config Mgmt',
        comingSoon: true,
      },
      {
        id: 'prometheus',
        name: 'Prometheus',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Monitoring',
        comingSoon: true,
      },
      {
        id: 'elk',
        name: 'ELK Stack',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Logging',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'frontend-engineering',
    name: 'Frontend Engineering',
    icon: Layout,
    color: 'pink',
    technologies: [
      {
        id: 'react',
        name: 'React',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Library',
        comingSoon: true,
      },
      {
        id: 'nextjs',
        name: 'Next.js',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Framework',
        comingSoon: true,
      },
      {
        id: 'typescript',
        name: 'TypeScript',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Language',
        comingSoon: true,
      },
      {
        id: 'tailwind',
        name: 'Tailwind CSS',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Styling',
        comingSoon: true,
      },
      {
        id: 'state-mgmt',
        name: 'Redux / Zustand',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'State Mgmt',
        comingSoon: true,
      },
      {
        id: 'web-performance',
        name: 'Web Performance',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Optimization',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'programming-languages',
    name: 'Programming Languages',
    icon: Terminal,
    color: 'cyan',
    technologies: [
      {
        id: 'java-lang',
        name: 'Java',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'OOP & JVM',
        comingSoon: true,
      },
      {
        id: 'python-lang',
        name: 'Python',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Dynamic',
        comingSoon: true,
      },
      {
        id: 'javascript-lang',
        name: 'JavaScript',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Event Loop',
        comingSoon: true,
      },
      {
        id: 'go-lang',
        name: 'Go',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Concurrency',
        comingSoon: true,
      },
      {
        id: 'rust-lang',
        name: 'Rust',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Memory Safety',
        comingSoon: true,
      },
      {
        id: 'cpp-lang',
        name: 'C++',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Systems',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'system-design',
    name: 'System Design',
    icon: Activity,
    color: 'indigo',
    technologies: [
      {
        id: 'scalability',
        name: 'Scalability & Availability',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Concepts',
        comingSoon: true,
      },
      {
        id: 'load-balancing',
        name: 'Load Balancing',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Distribution',
        comingSoon: true,
      },
      {
        id: 'caching-patterns',
        name: 'Caching Patterns',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Performance',
        comingSoon: true,
      },
      {
        id: 'sharding',
        name: 'Database Sharding',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Data Scale',
        comingSoon: true,
      },
      {
        id: 'cap-theorem',
        name: 'CAP Theorem',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Theory',
        comingSoon: true,
      },
      {
        id: 'distributed-consensus',
        name: 'Distributed Consensus',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Paxos/Raft',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'dsa',
    name: 'Data Structures & Algo',
    icon: GitBranch,
    color: 'teal',
    technologies: [
      {
        id: 'arrays-strings',
        name: 'Arrays & Strings',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Fundamental',
        comingSoon: true,
      },
      {
        id: 'trees-graphs',
        name: 'Trees & Graphs',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Hierarchical',
        comingSoon: true,
      },
      {
        id: 'dp',
        name: 'Dynamic Programming',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Optimization',
        comingSoon: true,
      },
      {
        id: 'sorting',
        name: 'Sorting & Searching',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Algorithms',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'security',
    name: 'Security Engineering',
    icon: Shield,
    color: 'yellow',
    technologies: [
      {
        id: 'oauth',
        name: 'OAuth 2.0 & OIDC',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Auth',
        comingSoon: true,
      },
      {
        id: 'jwt',
        name: 'JWT & Sessions',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Tokens',
        comingSoon: true,
      },
      {
        id: 'https',
        name: 'HTTPS & TLS',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Encryption',
        comingSoon: true,
      },
      {
        id: 'owasp',
        name: 'OWASP Top 10',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Vulnerabilities',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'ai-engineering',
    name: 'AI & ML Engineering',
    icon: Brain,
    color: 'fuchsia',
    technologies: [
      {
        id: 'llms',
        name: 'Large Language Models',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'GenAI',
        comingSoon: true,
      },
      {
        id: 'rag',
        name: 'RAG',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Retrieval',
        comingSoon: true,
      },
      {
        id: 'vector-dbs',
        name: 'Vector Databases',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Embeddings',
        comingSoon: true,
      },
      {
        id: 'mlops',
        name: 'MLOps',
        hasVisualizer: false,
        hasDoc: false,
        badge: 'Operations',
        comingSoon: true,
      },
    ],
  },
];

// Helper to get technology by ID across all categories
export const getTechnologyById = (techId) => {
  for (const category of categories) {
    const tech = category.technologies.find(t => t.id === techId);
    if (tech) {
      return { ...tech, category };
    }
  }
  return null;
};

// Helper to get category by ID
export const getCategoryById = (categoryId) => {
  return categories.find(c => c.id === categoryId);
};
